spring:
  profiles:
    active: google, meetup
server:
  port: ${PORT:8080}
logging:
  level:
    org.bdxjug: ${LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

bdxjug:
    google-sheet:
        key: ${GOOGLE_SHEET_API_KEY}
    meetup:
        group: "BordeauxJUG"
        key: ${MEETUP_API_KEY}
        oauth2:
          consumer-key: ${MEETUP_CONSUMER_KEY}
          consumer-secret: ${MEETUP_CONSUMER_SECRET}
          redirect-uri: ${MEETUP_REDIRECT_URI}
          




